### ISSUE TITLE
Failed to resolve import "@vueuse/core"

### ISSUE THREAD

**Issue by mullaney** [nuxt-themes/typography#55]
i'm working on a new installation using Nuxt 3. Below is my package.json:

```
{
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@nuxt-themes/typography": "^0.11.0",
    "@nuxt/content": "^2.5.2",
    "nuxt": "^3.2.3",
    "sass": "^1.60.0",
    "sass-loader": "^13.2.2"
  }
}

Here is the full branch: https://github.com/mullaney/new-kevin-kelly-nuxt/tree/add-%40nuxt-themes/typography

When I run this branch in development and go to `/logs/becoming-an-expert-reducer` I get the following error:

```
 ERROR  8:06:28 AM [vite] Internal server error: Failed to resolve import "@vueuse/core" from "node_modules/@nuxt-themes/typography/components/ProseCodeCopyButton.vue". Does the file exist?                                08:06:28
  Plugin: vite:import-analysis
  File: /Users/kevinkelly/Code/new-kevin-kelly-dev-blog/node_modules/@nuxt-themes/typography/components/ProseCodeCopyButton.vue:5:47
  3  |  import { defineComponent as _defineComponent } from "vue";
  4  |  import { ref } from "vue";
  5  |  import { useClipboard, onClickOutside } from "@vueuse/core";
     |                                                ^
  6  |  const _sfc_main = /* @__PURE__ */ _defineComponent({
  7  |    __name: "ProseCodeCopyButton",
      at formatError (file:///Users/kevinkelly/Code/new-kevin-kelly-dev-blog/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41418:46)
      at TransformContext.error (file:///Users/kevinkelly/Code/new-kevin-kelly-dev-blog/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41414:19)
      at normalizeUrl (file:///Users/kevinkelly/Code/new-kevin-kelly-dev-blog/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39706:33)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async TransformContext.transform (file:///Users/kevinkelly/Code/new-kevin-kelly-dev-blog/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39840:47)
      at async Object.transform (file:///Users/kevinkelly/Code/new-kevin-kelly-dev-blog/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
      at async loadAndTransform (file:///Users/kevinkelly/Code/new-kevin-kelly-dev-blog/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29)
```

**Comment by mullaney** [comment]
This is a duplicate of https://github.com/nuxt-themes/typography/issues/49

**Comment by Tahul** [comment]
This is a duplicate of #49 and will be tracked there!

Thanks for reporting it though! :)
